name: Cost_Net

device: 2
data:
  dataset: nogrid
  batch_size: 64
  X_list: [12,11,10,9,8,7,6,5,4,3,2,1]
  Y_list: [0,1,2,3,4,5,6,7,8,9,10,11]
  _len: [672,672]

batch_size_base: 64

train:
  epochs: 400
  max_grad_norm: 5
  early_stop_steps: 10


optimizer:
  name: Adam
  Adam:
    lr: 0.001
    weight_decay: 0.001
  RMSprop:
    lr: 0.01
    weight_decay: .001

optimizerbase:
  name: Adam
  Adam:
    lr: 0.003
    weight_decay: 0.001
  RMSprop:
    lr: 0.01
    weight_decay: .001

loss:
  name: rmse

model:
  name: Costnet
  Costnet:
    n_hist: 12
    n_pred: 12
    n_rnn_layers: 2
    hidden_size: 50
    input_dim: 2
    output_dim: 2
    node_num: 250
    decay_steps: 200
Base:
  name: SvdDecompose
  LinearDecompose:
    hidden_size: 50
    hidden_layer1: 300
    hidden_layer2: 150
    input_dim: 2
    output_dim: 2
    node_num: 250
  SvdDecompose:
    hidden_size: 50



scheduler:
  name: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.1
    patience: 2
    threshold: 0.001
    min_lr: 0.000001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [20, 30, 40, 50]
    gamma: 0.1