name: FC-LSTM

device: 2
data:
  dataset: nogrid
  batch_size: 32
  X_list: [12,11,10,9,8,7,6,5,4,3,2,1]
  Y_list: [0,1,2,3,4,5,6,7,8,9,10,11]
  _len: [672,672]


train:
  epochs: 200
  max_grad_norm: 5
  early_stop_steps: 10

optimizer:
  name: Adam
  Adam:
    lr: 0.002
    weight_decay: 0.001
  RMSprop:
    lr: 0.01
    weight_decay: .001

loss:
  name: rmse

model:
  name: FCLSTM
  FCLSTM:
    n_hist: 12
    n_pred: 12
    hidden_size: 150
    n_rnn_layers: 2
    input_dim: 2
    output_dim: 2
    decay_steps: 100

scheduler:
  name: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.1
    patience: 2
    threshold: 0.001
    min_lr: 0.000001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [20, 30, 40, 50]
    gamma: 0.1